version: '3'

services:
  cache:
    image: pinecone/redis
    ports:
      - "6379:6379"

  mongo:
    image: pinecone/mongo
    ports:
      - "27017:27017"

  message_queue:
    image: pinecone/message_queue
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"

